import type { ConditionType } from './conditionSymbols';

/** Grid position on the 10×4 symbol palette (row 0 = weather row 1, etc.). */
export const SPRITE_GRID: Record<ConditionType, { row: number; col: number }> = {
  clear: { row: 0, col: 0 },
  partly_cloudy: { row: 0, col: 1 },
  cloudy: { row: 0, col: 2 },
  mist: { row: 0, col: 3 },
  fog: { row: 0, col: 4 },
  light_rain: { row: 0, col: 5 },
  heavy_rain: { row: 0, col: 6 },
  snow: { row: 0, col: 7 },
  sleet: { row: 0, col: 8 },
  thunderstorm: { row: 0, col: 9 },
  strong_wind: { row: 1, col: 0 },
  high_winds: { row: 1, col: 1 },
  high_temp: { row: 1, col: 2 },
  low_temp: { row: 1, col: 3 },
  high_humidity: { row: 1, col: 4 },
  low_humidity: { row: 1, col: 5 },
  low_visibility: { row: 1, col: 6 },
  high_uv: { row: 1, col: 7 },
  icing: { row: 1, col: 8 },
  hail: { row: 1, col: 9 },
  solar: { row: 1, col: 7 },
  dust: { row: 1, col: 5 },
  general_alert: { row: 2, col: 0 },
  storm_warning: { row: 2, col: 1 },
  flood_risk: { row: 2, col: 2 },
  landslide_risk: { row: 2, col: 3 },
  wildfire_risk: { row: 2, col: 4 },
  seismic_activity: { row: 2, col: 5 },
  hazmat_alert: { row: 2, col: 6 },
  air_pollution: { row: 2, col: 7 },
  debris_on_track: { row: 2, col: 8 },
  vegetation_risk: { row: 2, col: 9 },
  all_clear: { row: 3, col: 0 },
  good_signal: { row: 3, col: 1 },
  weak_signal: { row: 3, col: 2 },
  no_signal: { row: 3, col: 3 },
  track_clear: { row: 3, col: 4 },
  track_caution: { row: 3, col: 5 },
  track_blocked: { row: 3, col: 6 },
  maintenance: { row: 3, col: 7 },
  station_active: { row: 3, col: 8 },
  port_active: { row: 3, col: 9 },
};

export const PALETTE_COLS = 10;
export const PALETTE_ROWS = 4;
